# Site settings
title: Finnix Blog
description: Finnix development weblog
author: Ryan Finnie
baseurl: ""
url: "https://blog.finnix.org"
permalink: /:year/:month/:day/:title/
git_web_base: https://github.com/rfinnie/jekyll-finnix/blob/main/
top_links:
  - {title: "Download", url: "http://www.finnix.org/Download"}
  - {title: "Wiki", url: "http://www.finnix.org/"}
keep_files:
  - .git
  - blog-media
include:
  - blog-media
cse_id: "015291346489371011935:0kqvmyejwjy"

# Build settings
markdown: kramdown
